project: 
  type: website
  
website: 
  page-navigation: true
  title: "Zarr Visualization Report"
  repo-url: https://github.com/nasa-impact/zarr-visualization-report 
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By NASA, 2023"
    
  sidebar:
    logo: "images/impact-logo.png"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/NASA-IMPACT/zarr-visualization-report
        text: "Zarr Visualization Report"
       

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - section: approaches/index.qmd
        contents: 
          - section: approaches/tiling.qmd
            contents:
            - approaches/tiling/benchmarking-methodology.qmd
            - approaches/tiling/results-and-recommendations.md
            - approaches/tiling/01-cmip6-cog-tile-server-benchmarks.ipynb
            - approaches/tiling/02-cog-zarr-kerchunk.ipynb
            - approaches/tiling/03-zarr-chunk-sizes.ipynb
            - approaches/tiling/04-number-of-spatial-chunks.ipynb
            - approaches/tiling/05-cmip6-pyramids.ipynb
            - approaches/tiling/tile-server-e2e-benchmarks.ipynb
            - approaches/tiling/future-areas.md
          - section: approaches/dynamic-client.qmd
            contents:
            - approaches/dynamic-client/prototype-deployment.qmd
            - approaches/dynamic-client/benchmarking-methodology.qmd
            - approaches/dynamic-client/e2e-results.ipynb
            - approaches/dynamic-client/e2e-results-zarr-version.ipynb
            - approaches/dynamic-client/e2e-results-zarr-version-shards.ipynb
            - approaches/dynamic-client/e2e-results-projection.ipynb
            - approaches/dynamic-client/e2e-results-shard-size.ipynb
            - approaches/dynamic-client/e2e-results-pixels-per-tile.ipynb
            - approaches/dynamic-client/e2e-results-aws-region.ipynb
            - approaches/dynamic-client/recommendations.qmd
            - approaches/dynamic-client/costs.ipynb
            - approaches/dynamic-client/future-areas.qmd 
          - href: approaches/tradeoffs.qmd





format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    toc: true


filters:
  - include-files.lua
  - quarto

  
